name: nova_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  connectivity_plus: ^7.0.0
  dartssh2: ^2.13.0
  file_picker: ^8.0.0
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
